typography_spectrum: 0.833176854532212
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8895174243953079
  lightness: 0.26879034168086946
  saturation: 0.7301830046344548
  rhythmicContrast: 0.632755569415167
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9708794481121004
analytics:
  google: null
  facebook: null
  twitter: null
name: SoundInsect
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: test
purpose: []
